# Generated by Django 5.2.17 on 2026-09-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("po_code", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateField()),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("vendor", models.CharField(max_length=255)),
                ("project_code", models.CharField(blank=True, max_length=50)),
                ("payment_term", models.CharField(blank=True, max_length=255)),
                ("currency", models.CharField(blank=True, max_length=10)),
                (
                    "net_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "received_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "invoiced_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "paid_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("source_state", models.CharField(blank=True, max_length=50)),
                ("dlv_status", models.CharField(blank=True, max_length=50)),
                ("last_imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending review"),
                            ("in_progress", "In progress"),
                            ("on_hold", "On hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_review",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-order_date", "po_code"],
            },
        ),
    ]
