# Generated by Django 5.2.17 on 2026-09-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="eta_status",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
